### ISSUE TITLE
Add ability to change tag type

### ISSUE THREAD

**Issue by wesley-dean** [wesley-dean/publish_container#16]
## Is your feature request related to a problem? Please describe.

Someone may want to use the tool to publish night builds

## Describe the solution you'd like

docker/megadata-action accepts a `type` for tags:

- semver (what we're using now)
- schedule
- a few others that might be trickier to implement

docs: https://github.com/docker/metadata-action#tags-input

```yaml
---
# other stuff
  uses: wesley-dean/publish_imagev1
  with:
    tag_type: schedule
```

## Describe alternatives you've considered

:shrug:

## Additional context

This may not be a big deal and nobody's asked for it.
