### ISSUE TITLE
Add marketplace branding

### ISSUE THREAD

**Issue by wesley-dean** [wesley-dean/publish_container#18]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

Add branding to action.yml

```yaml
branding:
  icon: 'arrow-up-circle'
  color: 'blue'

author: Wes Dean

```

https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#branding
